Import('*')

SimObject('HelloObject.py', sim_objects = ['HelloObject', 'GoodbyeObject'])
SimObject('SimpleMemobj.py', sim_objects = ['SimpleMemobj'])
SimObject('SimpleCache.py'. sim_objects = ['SimpleCache'])

Source('hello_object.cc')
Source('goodbye_object.cc')
Source('simple_memobj.cc')
Source('simple_cache.cc')

DebugFlag('Hello')
DebugFlag('SimpleMemobj')
DebugFlag('SimpleCache')
